import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, ManyToOne, JoinColumn, Index } from "typeorm";
import { Item } from "./item.model";
import { Warehouse } from "./warehouse.model";
import { User } from "../user.model";

/**
 * Inventory Alert Entity
 * 
 * Represents alerts generated by the inventory system.
 * Used for low stock notifications, expiration warnings, and other inventory-related alerts.
 */
@Entity("inventory_alerts")
@Index(["isActive"])
export class InventoryAlert {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ name: "alert_type", length: 50 })
  alertType: string; // 'low_stock', 'out_of_stock', 'expiration', 'quality_issue', etc.

  @ManyToOne(() => Item)
  @JoinColumn({ name: "item_id" })
  item: Item;

  @ManyToOne(() => Warehouse, { nullable: true })
  @JoinColumn({ name: "warehouse_id" })
  warehouse: Warehouse;

  @Column({ type: "text" })
  message: string;

  @Column({ name: "is_active", default: true })
  isActive: boolean;

  @Column({ name: "is_acknowledged", default: false })
  isAcknowledged: boolean;

  @ManyToOne(() => User, { nullable: true })
  @JoinColumn({ name: "acknowledged_by" })
  acknowledgedBy: User;

  @Column({ name: "acknowledged_at", type: "timestamp", nullable: true })
  acknowledgedAt: Date;

  @CreateDateColumn({ name: "created_at" })
  createdAt: Date;

  @UpdateDateColumn({ name: "updated_at" })
  updatedAt: Date;
}